### ISSUE TITLE
警告、エラーの修正依頼

### ISSUE THREAD

**Issue by pf-suzuki** [pf-tamura/todo_ts#1]
`npm run serve`したところ、下記の警告およびエラーが表示されました。
こちらの修正をお願いします。

```bash
Module Warning (from ./node_modules/eslint-loader/index.js):
warning: Delete `··` (prettier/prettier) at src/Options.ts:2:3:
  1 | const options: any[] = [
> 2 |     { value: -1, label: "すべて" },
    |   ^
  3 |     { value: 0, label: "作業中" },
  4 |     { value: 1, label: "完了" }
  5 |   ];


warning: Replace `····` with `··` (prettier/prettier) at src/Options.ts:3:1:
  1 | const options: any[] = [
  2 |     { value: -1, label: "すべて" },
> 3 |     { value: 0, label: "作業中" },
    | ^
  4 |     { value: 1, label: "完了" }
  5 |   ];
  6 | export default options;


warning: Replace `····` with `··` (prettier/prettier) at src/Options.ts:4:1:
  2 |     { value: -1, label: "すべて" },
  3 |     { value: 0, label: "作業中" },
> 4 |     { value: 1, label: "完了" }
    | ^
  5 |   ];
  6 | export default options;


warning: Delete `··` (prettier/prettier) at src/Options.ts:5:1:
  3 |     { value: 0, label: "作業中" },
  4 |     { value: 1, label: "完了" }
> 5 |   ];
    | ^
  6 | export default options;


warning: Insert `⏎` (prettier/prettier) at src/Options.ts:6:24:
  4 |     { value: 1, label: "完了" }
  5 |   ];
> 6 | export default options;
    |                        ^


5 warnings found.
5 warnings potentially fixable with the `--fix` option.

Module Warning (from ./node_modules/eslint-loader/index.js):
warning: Insert `⏎` (prettier/prettier) at src/components/Sort.vue:38:10:
  36 |   }
  37 | }
> 38 | </script>
     |          ^


1 warning found.
1 warning potentially fixable with the `--fix` option.

Module Warning (from ./node_modules/eslint-loader/index.js):
warning: Replace `=` with `·=·` (prettier/prettier) at src/App.vue:3:35:
  1 | <template>
  2 |   <div id="app">
> 3 |     <Header v-on:scurrent="current=$event" :counter="todos.length"></Header>
    |                                   ^
  4 |     <Main
  5 |       class="main"
  6 |       :computedTodos="computedTodos"


warning: Replace `=` with `·=·` (prettier/prettier) at src/App.vue:11:32:
   9 |       v-on:s_remove="doRemove($event)"
  10 |     ></Main>
> 11 |     <Sort v-on:s_select="select=$event" :select="select"></Sort>
     |                                ^
  12 |     <Form v-on:notify="todos=$event"></Form>
  13 |   </div>
  14 | </template>


warning: Replace `=` with `·=·` (prettier/prettier) at src/App.vue:12:29:
  10 |     ></Main>
  11 |     <Sort v-on:s_select="select=$event" :select="select"></Sort>
> 12 |     <Form v-on:notify="todos=$event"></Form>
     |                             ^
  13 |   </div>
  14 | </template>
  15 |


error: 'aComment' is already defined (no-redeclare) at src/App.vue:59:15:
  57 |           return aComment < bComment ? -1 : 1;
  58 |         case 5:
> 59 |           var aComment = a.comment;
     |               ^
  60 |           var bComment = b.comment;
  61 |           return aComment < bComment ? 1 : -1;
  62 |       }


error: 'bComment' is already defined (no-redeclare) at src/App.vue:60:15:
  58 |         case 5:
  59 |           var aComment = a.comment;
> 60 |           var bComment = b.comment;
     |               ^
  61 |           return aComment < bComment ? 1 : -1;
  62 |       }
  63 |     });


warning: Replace `else` with `·else·` (prettier/prettier) at src/App.vue:73:6:
  71 |     if (item.state === 1) {
  72 |       item.datef = new Date().getTime();
> 73 |     }else{
     |      ^
  74 |       item.datef = -1;
  75 |     }
  76 |   }


warning: Delete `⏎` (prettier/prettier) at src/App.vue:117:1:
  115 | }
  116 | </style>
> 117 |
      | ^
  118 |


2 errors and 5 warnings found.
5 warnings potentially fixable with the `--fix` option.

Module Warning (from ./node_modules/eslint-loader/index.js):
warning: Replace `{{·menu.value·}}` with `⏎············{{·menu.value·}}⏎··········` (prettier/prettier) at src/components/Main.vue:6:69:
  4 |       <tr>
  5 |         <th v-for="menu in ths" v-bind:key="menu.id">
> 6 |           <button v-on:click="s_id(menu)" type="button" class="aaa">{{ menu.value }}</button>
    |                                                                     ^
  7 |         </th>
  8 |       </tr>
  9 |     </thead>


warning: Replace `·v-for="item·in·computedTodos"·v-bind:key="item.id"·v-bind:class="{done:item.state}"` with `⏎········v-for="item·in·computedTodos"⏎········v-bind:key="item.id"⏎········v-bind:class="{·done:·item.state·}"⏎······` (prettier/prettier) at src/components/Main.vue:11:10:
   9 |     </thead>
  10 |     <tbody>
> 11 |       <tr v-for="item in computedTodos" v-bind:key="item.id" v-bind:class="{done:item.state}">
     |          ^
  12 |         <th>{{ item.id }}</th>
  13 |         <td>{{ item.comment }}</td>
  14 |         <td class="state">


2 warnings found.
2 warnings potentially fixable with the `--fix` option.
```

**Comment by pf-suzuki** [comment]
エラーになっている箇所はなぜエラーになっているかも考えてみてください。
